#!/bin/sh
testDir=`dirname $0`
(
cd $testDir
rm -r bin/
mkdir -p bin
curl "http://build.partario.com/guestAuth/repository/download/bt2/.lastSuccessful/NPackage.zip" > bin/NPackage.zip
unzip bin/NPackage.zip -d bin/
rm -r lib/.dist lib/*
exec mono bin/NPackage.exe install \
    fsharp.core \
    log4net \
    mono.cecil \
    mono.options \
    nhibernate \
    npackage \
    ravendb.client \
    ravendb.server \
    rhino.mocks \
    nunit \
    sharpziplib \

#    json \
#    quickgraph \

)
