#!/bin/sh
scriptsDir=`dirname $0`
binDir=$scriptsDir/bin
mkdir -p $binDir
curl "http://build.partario.com/guestAuth/repository/download/bt2/.lastSuccessful/NPackage.zip" > $binDir/NPackage.zip
unzip -o bin/NPackage.zip -d $binDir/
rm $binDir/NPackage.exe.config
exec mono $binDir/NPackage.exe install json mono.options nunit sharpziplib
